### ISSUE TITLE
Unexpected error in innerDocument 

### ISSUE THREAD

**Issue by antoinelyset** [jwysiwyg/jwysiwyg#326]
Hi,

I got this error :

```
 Unexpected error in innerDocument 
```
and :
```
Uncaught TypeError: Object #<HTMLIFrameElement> has no method 'open'
```
I use jwysiwyg in a Twitter Bootstrap Modal.

 I investigated myself and I think it could happen when the innerDocument method tries to access to element.contentDocument (I use Chrome) before the iframe is up and running totally. (see [https://github.com/akzhan/jwysiwyg/blob/master/jquery.wysiwyg.js#L1606](https://github.com/akzhan/jwysiwyg/blob/master/jquery.wysiwyg.js#L1606))

Thanks.

**Comment by antoinelyset** [comment]
I think this issue is old and misleading.

Thanks for you work guys.

**Comment by CME64** [comment]
I think the issue should be re-opened
the wysiwyg library doesn't execute synchronously (non blocking) which will make it break if any major alteration to the field is done right after the attachment of the wysiwyg to it. This behaviour should be changed and made synchronous.
e.g.
$('#elm').wysiwyg();
$('#elm').remove();

I'm using version 0.98 dev
