### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by sedrubal** [jwysiwyg/jwysiwyg#383]
I'd be nice if one could install jwysiwyg with [bower](bower.io). The [fork](https://github.com/akzhan/jwysiwyg) by @akzhan is already on bower but this repo is not.

**Comment by akzhan** [comment]
I have nothing of https://github.com/akzhan/jwysiwyg about bower.

But idea;s good.

**Comment by akzhan** [comment]
Looks like handled by #385.

**Comment by sedrubal** [comment]
Great, thanks. Have you already registered the package? I can't find it with `bower search jwysiwyg`.

**Comment by akzhan** [comment]
It was registered earlier I think.

```
➜  jwysiwyg git:(master) bower register jwysiwyg https://github.com/jwysiwyg/jwysiwyg.git
bower jwysiwyg#*               resolve https://github.com/jwysiwyg/jwysiwyg.git#*
bower jwysiwyg#*              checkout 0.97.2
bower jwysiwyg#*              resolved https://github.com/jwysiwyg/jwysiwyg.git#0.97.2
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower jwysiwyg                register https://github.com/jwysiwyg/jwysiwyg.git
bower                       EDUPLICATE Duplicate package
```

**Comment by sedrubal** [comment]
Yes, I think you registered your fork 😁

https://github.com/akzhan/jwysiwyg

**Comment by akzhan** [comment]
Thanks, reregister as jwysiwyg/jwysiwyg.

And repositories now updated to be in sync.

**Comment by sedrubal** [comment]
Thank you very much :D
